from __future__ import annotations

from typing import Iterable, Optional, Protocol

from ism.domain.models import Product, PurchaseHeader, PurchaseLine, SaleHeader, SaleLine, User


class ProductRepository(Protocol):
    def list_products(self) -> list[Product]: ...
    def get_product_by_id(self, product_id: int) -> Optional[Product]: ...
    def get_product_by_sku(self, sku: str) -> Optional[Product]: ...
    def upsert_product(self, sku: str, name: str, cost_usd: float, price_usd: float, stock: int, min_stock: int) -> int: ...
    def deactivate_product(self, product_id: int) -> bool: ...

class SalesRepository(Protocol):
    def create_sale(self, datetime_iso: str, fx_usd_ars: float, notes: Optional[str], items: Iterable[dict], actor_user_id: int | None = None) -> int: ...
    def list_sales_between(self, start_iso: str, end_iso: str) -> list[SaleHeader]: ...
    def get_sale_header(self, sale_id: int) -> Optional[SaleHeader]: ...
    def sale_items_for_sale(self, sale_id: int) -> list[SaleLine]: ...
    def sales_summary_between(self, start_iso: str, end_iso: str): ...


class PurchaseRepository(Protocol):
    def create_purchase_with_items(self, datetime_iso: str, vendor: Optional[str], total_usd: float, notes: Optional[str], items: Iterable[dict], actor_user_id: int | None = None) -> int: ...
    def list_purchases_between(self, start_iso: str, end_iso: str) -> list[PurchaseHeader]: ...
    def purchase_items_for_purchase(self, purchase_id: int) -> list[PurchaseLine]: ...


class AuthRepository(Protocol):
    def list_users(self) -> list[User]: ...
    def authenticate_user(self, username: str, pin: str) -> Optional[User]: ...
    def create_user(self, username: str, pin: str, role: str) -> int: ...
    def change_user_pin(self, user_id: int, current_pin: str, new_pin: str) -> bool: ...